<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="lon-7390-182" failures="1" tests="2" name="Default test(failed)" time="0.059" errors="0" timestamp="2021-07-27T21:09:19 BST">
  <testcase classname="retry.TestNGRetry" name="test3" time="0.013">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at retry.TestNGRetry.test3(TestNGRetry.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="retry.TestNGRetry" name="test2" time="0.002"/>
  <testcase classname="retry.TestNGRetry" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
